services:
  postgres:
    image: postgres:16-alpine
    container_name: vokabeln_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vokabeln
      POSTGRES_PASSWORD: vokabeln
      POSTGRES_DB: vokabeln
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
